global using System.Runtime.CompilerServices;
global using Ardalis.SharedKernel;
global using HospitalManagementSystem.Core.ContributorAggregate;
global using HospitalManagementSystem.UseCases.Contributors.Create;
global using Shouldly;
global using Mediator;
global using Microsoft.Extensions.Logging;
global using NSubstitute;
global using Xunit;
